from .accept_attr import Accept
from .accept_charset_attr import AcceptCharset
from .action_attr import Action
from .allow_attr import Allow
from .alt_attr import Alternative
from .aria_attr import ARIA
from .as_attr import As
from .async_attr import Asynchronous
from .autocomplete_attr import Autocomplete
from .autoplay_attr import Autoplay
from .buffered_attr import Buffered
from .capture_attr import Capture
from .charset_attr import CharacterSet
from .checked_attr import Checked
from .cite_attr import Cite
from .color_attr import Color
from .cols_attr import Columns
from .colspan_attr import ColumnSpan
from .content_attr import Content
from .controls_attr import Controls
from .coords_attr import Coordinates
from .crossorigin_attr import CrossOrigin
from .currentTime_attr import CurrentTime
from .custom_data_attr import CustomData
from .data_attr import Data
from .datetime_attr import DateTime
from .decoding_attr import Decoding
from .default_attr import Default
from .defer_attr import Defer
from .dirname_attr import DirectionName
from .disabled_attr import Disabled
from .download_attr import Download
from .enctype_attr import EncodingType
from .event_handler_attr import EventHandler
from .for_attr import For
from .form_attr import Form
from .formaction_attr import FormAction
from .formenctype_attr import FormEncodingType
from .formmethod_attr import FormMethod
from .formnovalidate_attr import FormNoValidate
from .formtarget_attr import FormTarget
from .global_attr import Global
from .headers_attr import Headers
from .height_attr import Height
from .high_attr import High
from .href_attr import HypertextReference
from .hreflang_attr import HypertextReferenceLanguage
from .http_equiv_attr import HTTPEquivalent
from .imagesizes_attr import ImageSizes
from .imagesrcset_attr import ImageSourceSet
from .integrity_attr import Integrity
from .kind_attr import Kind
from .label_attr import Label
from .list_attr import List
from .loop_attr import Loop
from .low_attr import Low
from .max_attr import Maximum
from .maxlength_attr import MaximumLength
from .media_attr import Media
from .method_attr import Method
from .min_attr import Minimum
from .minlength_attr import MinimumLength
from .multiple_attr import Multiple
from .muted_attr import Muted
from .name_attr import Name
from .novalidate_attr import NoValidate
from .open_attr import Open
from .optimum_attr import Optimum
from .pattern_attr import Pattern
from .ping_attr import Ping
from .placeholder_attr import Placeholder
from .playsinline_attr import PlaysInline
from .poster_attr import Poster
from .preload_attr import Preload
from .readonly_attr import ReadOnly
from .referrerpolicy_attr import ReferrerPolicy
from .rel_attr import Relation
from .required_attr import Required
from .reversed_attr import Reversed
from .rows_attr import Rows
from .rowspan_attr import RowSpan
from .sandbox_attr import Sandbox
from .scope_attr import Scope
from .selected_attr import Selected
from .shape_attr import Shape
from .size_attr import Size
from .sizes_attr import Sizes
from .span_attr import Span
from .src_attr import Source
from .srcdoc_attr import SourceDocument
from .srclang_attr import SourceLanguage
from .srcset_attr import SourceSet
from .start_attr import Start
from .step_attr import Step
from .target_attr import Target
from .type_attr import Type
from .usemap_attr import UseMap
from .value_attr import Value
from .width_attr import Width
from .wrap_attr import Wrap
from .xmlns_attr import XMLNamespace

from .attribute_renderer import AttributeRenderer
